apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    # Using targetRevision as empty or '*' pulls the latest chart version
    targetRevision: '*'
    helm:
      values: |
        defaultSettings:
          # Sets the default replica count for volumes created from the UI
          defaultReplicaCount: 1
        persistence:
          # Sets the replica count for the Longhorn-provisioned default StorageClass
          defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
