apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: infra
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources: 
    repoURL: https://github.com/longhorn/longhorn.git
    targetRevision: 1.6.2
    path: deploy/longhorn.yaml
    helm:
      valuesObject:
        defaultSettings:
          defaultReplicaCount: 1
        persistence:
          defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
