apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-sa
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-10"
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              (kubectl get ns longhorn-system || kubectl create ns longhorn-system) && (kubectl get sa longhorn-service-account -n longhorn-system || kubectl create sa longhorn-service-account -n longhorn-system)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    # Using targetRevision as empty or '*' pulls the latest chart version
    targetRevision: '*'
    helm:
      values: |
        defaultSettings:
          # Sets the default replica count for volumes created from the UI
          defaultReplicaCount: 1
        persistence:
          # Sets the replica count for the Longhorn-provisioned default StorageClass
          defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-postgres
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.29.0
    chart: cloudnative-pg
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-sso
  namespace: argocd
  labels:
    app.kubernetes.io/name: keycloak-sso
spec:
  project: default
  source:
    repoURL: https://github.com/Sebastian-Nowaczyk-Elektrorecykling/manual-bootstrap.git
    targetRevision: main
    path: 02-keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
