apiVersion: v1
kind: Namespace
metadata:
  name: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    # Using targetRevision as empty or '*' pulls the latest chart version
    targetRevision: '*'
    helm:
      values: |
        defaultSettings:
          # Sets the default replica count for volumes created from the UI
          defaultReplicaCount: 1
        persistence:
          # Sets the replica count for the Longhorn-provisioned default StorageClass
          defaultClassReplicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-postgres
  namespace: infra
  labels:
    app.kubernetes.io/name: cloud-native-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: default
  source:
    repoURL: https://github.com/Sebastian-Nowaczyk-Elektrorecykling/manual-bootstrap.git
    targetRevision: main
    path: 01-db
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
